name: Cmake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install-Clang-Tidy
      working-directory: ${{runner.workspace}}
      shell: bash
      run: sudo apt-get update && sudo apt-get install clang-tidy
    
    - name: Run-Clang-Tidy
      shell: bash
      run: clang-tidy src/* -- -Iinclude

    - name: Create-Build-Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure-CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -R
